apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: react-app-release
  namespace: react-app
spec:
  interval: 5m
  chart:
    spec:
      chart: generic-chart
      version: "3.3.7"
      sourceRef:
        kind: HelmRepository
        name: alizandieh
        namespace: flux-system
      interval: 1m

  values:

    fullnameOverride: "react-app"

    image:
      repository: alizandieh2019/react_app
      tag: 1
      pullPolicy: Always
      
    containerPort: 80

